-- test123
INSERT INTO SECURITY_USER (PASSWORD, USERNAME) VALUES ('45B6UBkULmvQcUEBf4RfYw==', 'first');
-- test1234
INSERT INTO SECURITY_USER (PASSWORD, USERNAME) VALUES ('kWUQK+t+IRVBbUTU6QdafA==', 'second');
-- test1235
INSERT INTO SECURITY_USER (PASSWORD, USERNAME) VALUES ('SAG5FmI/uPf3ph/epnyflg==', 'third');
